version: '3.7'
services:
  backend:
    image: Panda-ManR/article_backend:latest
    container_name: article_backend
    healthcheck:
        test: ["CMD", "curl", "-f", "backend"]
        interval: 30s
        timeout: 10s
        retries: 5
    depends_on:
      - article_db
    ports:
      - 8080:8080
    volumes:
      - ./data/certbot/conf/live/${HOST}:/etc/certs

  article_db:
    image: Panda-ManR/article_db:latest
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    container_name: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      DB_NAME: "article"
      POSTGRES_DB: article
      PGPORT: 5432
      POPULATE_DB: ${POPULATE_DB}

volumes:
  data: {}
